// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/api/eltrafico.ts";
import * as $1 from "./routes/api/env.ts";
import * as $2 from "./routes/api/interfaces.ts";
import * as $3 from "./routes/api/netmonitor.ts";
import * as $4 from "./routes/index.tsx";
import * as $$0 from "./islands/App.tsx";

const manifest = {
  routes: {
    "./routes/api/eltrafico.ts": $0,
    "./routes/api/env.ts": $1,
    "./routes/api/interfaces.ts": $2,
    "./routes/api/netmonitor.ts": $3,
    "./routes/index.tsx": $4,
  },
  islands: {
    "./islands/App.tsx": $$0,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
