// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $api_eltrafico from "./routes/api/eltrafico.ts";
import * as $api_env from "./routes/api/env.ts";
import * as $api_interfaces from "./routes/api/interfaces.ts";
import * as $api_netmonitor from "./routes/api/netmonitor.ts";
import * as $index from "./routes/index.tsx";
import * as $App from "./islands/App.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/api/eltrafico.ts": $api_eltrafico,
    "./routes/api/env.ts": $api_env,
    "./routes/api/interfaces.ts": $api_interfaces,
    "./routes/api/netmonitor.ts": $api_netmonitor,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/App.tsx": $App,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
