#!/bin/bash
SELF=$(readlink -f "$0")
HERE=${SELF%/*}

export PATH="${HERE}/usr/bin/:${PATH}"
export DENO_DIR="${HERE}/bandito/vendor-x86-64"
export BANDITO_CACHE_DIR="${HOME}/.cache/bandito-deno"
mkdir -p "${BANDITO_CACHE_DIR}"

cp "${HERE}/usr/bin/eltrafico-tc" $BANDITO_CACHE_DIR
cp "${HERE}/usr/bin/bandwhich" $BANDITO_CACHE_DIR
export TC="${BANDITO_CACHE_DIR}/eltrafico-tc"
export MONITOR="bandwhich"
export BANDWHICH="${BANDITO_CACHE_DIR}/bandwhich"

cd "${HERE}/bandito"
exec "${HERE}/usr/bin/deno" run --allow-all --cached-only webview.ts "$@"
